services:
  netalertx:
    container_name: netalertx
    # use the below line if you want to test the latest dev image
    # image: "ghcr.io/jokob-sk/netalertx-dev:latest" 
    image: "ghcr.io/jokob-sk/netalertx:latest"      
    network_mode: "host"        
    restart: unless-stopped
    volumes:
      - /srv/infra/netalertx/config:/app/config
      - /srv/infra/netalertx/db:/app/db      
      # (optional) useful for debugging if you have issues setting up the container
      - /srv/infra/netalertx/logs:/app/log
      # (API: OPTION 1) use for performance
      - type: tmpfs
        target: /app/api
      # (API: OPTION 2) use when debugging issues 
      # -  ./api:/app/api
    environment:
      - TZ=America/Denver
      - PORT=20211
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.netalertx.entrypoints=websecure"
      - "traefik.http.routers.netalertx.rule=Host(`netalertx.burgoyne.casa`)"
      - "traefik.http.routers.netalertx.tls=true"
      - "traefik.http.routers.netalertx.tls.certresolver=letsencrypt"
      - "traefik.http.services.netalertx.loadbalancer.server.port=20211"